CREATE TABLE Orders (OrderID SERIAL PRIMARY KEY,
                    MemberID INT,
                    My_Size SIZE,
                    My_Crust CRUST,
                    My_Sauce SAUCE,
                    My_cheese CHEESE,
                    My_Ham BOOLEAN,
                    My_Beef BOOLEAN,
                    My_Salami BOOLEAN,
                    My_Pepperoni BOOLEAN,
                    My_Sausage BOOLEAN,
                    My_Chicken BOOLEAN,
                    My_Bacon BOOLEAN,
                    My_Steak BOOLEAN,
                    My_Buffalo BOOLEAN,
                    My_Garlic BOOLEAN,
                    My_Jalapeno BOOLEAN,
                    My_Onions BOOLEAN,
                    My_Banana BOOLEAN,
                    My_Tomatoes BOOLEAN,
                    My_Olives BOOLEAN,
                    My_Mushroom BOOLEAN,
                    My_Pineapple BOOLEAN,
                    My_Provolone BOOLEAN,
                    My_Cheddar BOOLEAN,
                    My_Green BOOLEAN,
                    My_Spinach BOOLEAN,
                    My_Red BOOLEAN,
                    My_Feta BOOLEAN,
                    My_Asiago BOOLEAN,
                    FOREIGN KEY(MemberID) REFERENCES Members(MemberID)
);